void event_channel(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_connect(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_ctcp_req(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_join(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_kick(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_nick(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_part(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_privmsg(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
void event_quit(irc_session_t *session, const char *event, const char *origin, const char **params, unsigned int count);
