void *threaded_channel(void *args);
void *threaded_connect(void *args);
void *threaded_join(void *args);
void *threaded_kick(void *args);
void *threaded_nick(void *args);
void *threaded_numeric(void *args);
void *threaded_part(void *args);
void *threaded_privmsg(void *args);
void *threaded_quit(void *args);
